const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
const COW_NAMES={
'1314':'Borboleta','3204':'Varanda','3226':'Mosquita','3233':'Formiga','3544':'Carcaça','3550':'Viola','3865':'Maria do Carmo','3868':'Rafaela','4280':'Lusitana','4281':'Laranja','4282':'Bandeira','4284':'Vitoria','4444':'Suíça','4688':'Toucada','4689':'Miranda','4690':'Benfica','5800':'Pintada','5803':'Carlota','6356':'Ratiça','6358':'Pipoca','6359':'Quadrada','6445':'Sete','6810':'Estrela','6811':'Estela','7713':'Rajada','7749':'Malvina','8662':'Marlene','9112':'Susena','9115':'Marcada','9211':'Mafalda','9212':'Janota','9700':'Margarida','9810':'Madalena','9975':'Mulata','9980':'Baixinha'
}
const STORAGE_KEY='lavoura-cow-names-v1'
let syncing=false
function saveLocal(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(COW_NAMES))}catch{}}
function decorate(){const main=document.querySelector('#app main');if(!main)return;for(const card of main.querySelectorAll('.cow-card')){const number=String(card.dataset.id||card.innerText.match(/🐄\s*([^\s]+)/)?.[1]||'').trim();const name=COW_NAMES[number];if(!name)continue;const text=card.querySelector('.cow-number')||card.querySelector('strong')||card.firstElementChild;if(text&&!text.innerText.includes(name))text.innerHTML=`🐄 ${number} <span class="muted">— ${name}</span>`}const title=main.querySelector('h1');if(title&&title.innerText.includes('🐄')){const number=title.innerText.match(/🐄\s*([^\s]+)/)?.[1]?.trim();const name=COW_NAMES[number];if(name&&!title.innerText.includes(name))title.textContent=`🐄 ${number} — ${name}`}}
async function syncNames(){if(syncing)return;const sb=window.lavouraSupabase;if(!sb)return;syncing=true;try{const {data,error}=await sb.from('animals').select('id,number,name').eq('farm_id',FARM_ID);if(error)return;for(const animal of data||[]){const name=COW_NAMES[String(animal.number)];if(!name||animal.name===name)continue;const {error:updateError}=await sb.from('animals').update({name}).eq('id',animal.id).eq('farm_id',FARM_ID);if(updateError)console.error('Cow name update:',animal.number,updateError)}}finally{syncing=false}}
saveLocal();decorate();syncNames().then(decorate);let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}).observe(document.body,{childList:true,subtree:true})
