const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
let busy=false
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function today(){return new Date().toISOString().slice(0,10)}
function dayDiff(v){if(!v)return 9999;const a=new Date(today()+'T00:00:00');const b=new Date(String(v).slice(0,10)+'T00:00:00');return Math.round((b-a)/86400000)}
function ptDate(v){if(!v)return'—';const[y,m,d]=String(v).slice(0,10).split('-');return`${d}/${m}/${y}`}
function statusText(days){if(days<0)return`${Math.abs(days)} dia(s) atrasado`;if(days===0)return'Hoje';if(days===1)return'Amanhã';return`em ${days} dias`}
function screenText(){return(document.querySelector('main.app')?.innerText||'').toLowerCase()}
function isMore(){const t=screenText();return t.includes('mais')&&t.includes('definições')}
function addEntry(){if(!isMore()||document.querySelector('[data-agenda-entry]'))return;const main=document.querySelector('main.app');if(!main)return;const card=document.createElement('section');card.className='card';card.dataset.agendaEntry='1';card.innerHTML='<h2>📅 Agenda da exploração</h2><p>Diagnósticos, secagens, partos e fim de carências num só sítio.</p><button type="button" data-agenda-action="open">Abrir agenda</button>';const back=[...main.querySelectorAll('button')].find(b=>b.textContent.includes('Voltar'));if(back)back.insertAdjacentElement('beforebegin',card);else main.appendChild(card)}
async function loadAgenda(){const sb=window.lavouraSupabase;if(!sb)throw new Error('Supabase indisponível');const[a,r,h]=await Promise.all([sb.from('animals').select('id,number').eq('farm_id',FARM_ID),sb.from('reproduction').select('animal_id,event_type,event_date,result,expected_dry_off,expected_calving').eq('farm_id',FARM_ID).order('event_date',{ascending:false}),sb.from('health_records').select('animal_id,medication,milk_withdrawal_until,meat_withdrawal_until').eq('farm_id',FARM_ID)]);if(a.error)throw a.error;if(r.error)throw r.error;if(h.error)throw h.error;const byId=new Map((a.data||[]).map(x=>[String(x.id),x.number]));const latestIA=new Map();for(const x of r.data||[]){if(String(x.event_type).toUpperCase()==='IA'&&!latestIA.has(String(x.animal_id)))latestIA.set(String(x.animal_id),x)}const items=[];for(const[animalId,x]of latestIA){const n=byId.get(animalId)||'—';const result=String(x.result||'').toLowerCase();if(!result&&-dayDiff(x.event_date)>=28){const date=new Date(String(x.event_date)+'T00:00:00');date.setDate(date.getDate()+28);items.push({date:date.toISOString().slice(0,10),icon:'🩺',title:`Diagnóstico vaca ${n}`,type:'Diagnóstico'})}if(result==='prenhe'||result.includes('positiv')){if(x.expected_dry_off)items.push({date:x.expected_dry_off,icon:'🟠',title:`Secagem vaca ${n}`,type:'Secagem'});if(x.expected_calving)items.push({date:x.expected_calving,icon:'🔵',title:`Parto vaca ${n}`,type:'Parto'})}}
for(const x of h.data||[]){const n=byId.get(String(x.animal_id))||'—';if(x.milk_withdrawal_until)items.push({date:x.milk_withdrawal_until,icon:'🥛',title:`Fim carência leite — vaca ${n}`,type:'Saúde',detail:x.medication});if(x.meat_withdrawal_until)items.push({date:x.meat_withdrawal_until,icon:'🥩',title:`Fim carência carne — vaca ${n}`,type:'Saúde',detail:x.medication})}
return items.filter(x=>{const d=dayDiff(x.date);return d>=-7&&d<=90}).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function render(items){const root=document.querySelector('#app');const overdue=items.filter(x=>dayDiff(x.date)<0),todayItems=items.filter(x=>dayDiff(x.date)===0),future=items.filter(x=>dayDiff(x.date)>0);const section=(title,list)=>`<section class="card"><h2>${title}</h2>${list.length?list.map(x=>`<article class="cow-card"><div><strong>${x.icon} ${esc(x.title)}</strong><div class="muted">${esc(x.type)}${x.detail?` · ${esc(x.detail)}`:''}</div></div><div class="right"><strong>${ptDate(x.date)}</strong><div class="muted">${statusText(dayDiff(x.date))}</div></div></article>`).join(''):'<p class="muted">Nada para mostrar.</p>'}</section>`;root.innerHTML=`<main class="app"><button class="secondary" data-agenda-action="back">← Voltar</button><h1>📅 Agenda da exploração</h1><p class="subtitle">Próximos 90 dias · atrasos até 7 dias</p>${overdue.length?section('🔴 Atrasado',overdue):''}${section('⭐ Hoje',todayItems)}${section('Próximos',future)}</main>`}
async function open(){if(busy)return;busy=true;try{render(await loadAgenda())}catch(e){alert('Não foi possível abrir a agenda: '+e.message)}finally{busy=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-agenda-action]');if(!b)return;e.preventDefault();if(b.dataset.agendaAction==='open')open();if(b.dataset.agendaAction==='back'){document.querySelector('[data-action="mais"]')?.click()||location.reload()}})
let queued=false;function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;addEntry()})}new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});addEntry()
