const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
const STYLE_ID='feed-tools-style'
let records=[]
let milk=[]
let busy=false

function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.feed-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.feed-stat{background:#fff;border:1px solid rgba(47,111,68,.14);border-radius:16px;padding:13px}.feed-stat span{display:block;font-size:12px;color:#68756d}.feed-stat strong{font-size:20px}.feed-form{display:grid;gap:10px}.feed-form label{display:grid;gap:5px;font-weight:700}.feed-form input,.feed-form select,.feed-form textarea{width:100%;box-sizing:border-box}.feed-form-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.feed-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:start}.feed-note{font-size:12px;color:#68756d}.feed-pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef5f0;font-size:12px;font-weight:700;margin:2px 4px 2px 0}
@media(max-width:700px){.feed-grid{grid-template-columns:1fr 1fr}.feed-form-row{grid-template-columns:1fr}.feed-row{grid-template-columns:1fr}.feed-form button{min-height:48px}}
`;document.head.appendChild(s)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function today(){return new Date().toISOString().slice(0,10)}
function ptDate(v){if(!v)return'—';const[y,m,d]=String(v).slice(0,10).split('-');return d&&m?`${d}/${m}/${y}`:v}
function euro(v){return Number(v||0).toLocaleString('pt-PT',{style:'currency',currency:'EUR'})}
function num(v,d=2){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-PT',{maximumFractionDigits:d,minimumFractionDigits:d}):'—'}
function screenText(){return(document.querySelector('main.app')?.innerText||'').toLowerCase()}
function isMore(){const t=screenText();return t.includes('mais')&&t.includes('definições')}
function latestMilk(){return [...milk].sort((a,b)=>String(b.record_date).localeCompare(String(a.record_date)))[0]||null}
function milkForDate(date){return milk.find(r=>r.record_date===date)||latestMilk()}
function costRow(r){const cows=Number(r.cows_fed||0),kg=Number(r.kg_per_cow||0),price=Number(r.price_per_kg||0);return cows*kg*price}
function latestDayRecords(){if(!records.length)return[];const date=[...records].map(r=>r.record_date).sort().at(-1);return records.filter(r=>r.record_date===date)}
function metrics(){const day=latestDayRecords();const feedDate=day[0]?.record_date||null;const totalCost=day.reduce((s,r)=>s+costRow(r),0);const production=feedDate?milkForDate(feedDate):latestMilk();const exactDate=Boolean(feedDate&&production?.record_date===feedDate);const liters=Number(production?.liters||0);const cows=Number(production?.milking_cows||day[0]?.cows_fed||0);const totalKgPerCow=day.reduce((s,r)=>s+Number(r.kg_per_cow||0),0);return{day,feedDate,production,exactDate,totalCost,liters,cows,totalKgPerCow,costPerCow:cows?totalCost/cows:0,costPerLiter:liters?totalCost/liters:0}}

async function load(){const sb=window.lavouraSupabase;if(!sb)throw new Error('Supabase indisponível');const[f,m]=await Promise.all([sb.from('feed_records').select('*').eq('farm_id',FARM_ID).order('record_date',{ascending:false}).order('created_at',{ascending:false}),sb.from('milk_records').select('record_date,liters,milking_cows').eq('farm_id',FARM_ID).order('record_date',{ascending:false}).limit(30)]);if(f.error)throw f.error;if(m.error)throw m.error;records=f.data||[];milk=m.data||[]}

function addMoreEntry(){if(!isMore()||document.querySelector('[data-feed-entry]'))return;const main=document.querySelector('main.app');if(!main)return;const card=document.createElement('section');card.className='card';card.dataset.feedEntry='1';card.innerHTML=`<h2>🌾 Alimentação</h2><p>Ração, milho, silagem e outros alimentos com custo por vaca e por litro.</p><button type="button" data-feed-action="open">Abrir alimentação</button>`;const back=[...main.querySelectorAll('button')].find(b=>b.textContent.includes('Voltar'));if(back)back.insertAdjacentElement('beforebegin',card);else main.appendChild(card)}

function render(){ensureStyle();const root=document.querySelector('#app');if(!root)return;const m=metrics();const latestDate=m.day[0]?.record_date;root.innerHTML=`<main class="app"><button class="secondary" type="button" data-feed-action="back">← Voltar</button><h1>🌾 Alimentação e custos</h1><p class="subtitle">Alimentação do rebanho ligada à produção</p><div class="feed-grid"><div class="feed-stat"><span>Kg/vaca/dia</span><strong>${num(m.totalKgPerCow,1)}</strong></div><div class="feed-stat"><span>Custo/vaca/dia</span><strong>${euro(m.costPerCow)}</strong></div><div class="feed-stat"><span>Custo alimentar/L</span><strong>${m.liters?euro(m.costPerLiter):'—'}</strong></div><div class="feed-stat"><span>Custo diário</span><strong>${euro(m.totalCost)}</strong></div></div><section class="card"><p class="feed-note">${latestDate?`Alimentação de ${ptDate(latestDate)}${m.production?` · produção de ${ptDate(m.production.record_date)} (${num(m.liters,0)} L)${m.exactDate?'':' — data mais recente disponível'}`:''}.`:'Ainda não há alimentação registada.'}</p><button type="button" data-feed-action="new">＋ Registar alimento</button></section><section class="card"><h2>Histórico</h2>${records.length?records.slice(0,40).map(r=>`<article class="cow-card feed-row"><div><strong>${ptDate(r.record_date)} · ${esc(r.feed_type)}</strong><div>${esc(r.product_name||'')}</div><div><span class="feed-pill">${num(r.kg_per_cow,2)} kg/vaca</span><span class="feed-pill">${Number(r.cows_fed||0)} vacas</span><span class="feed-pill">${euro(r.price_per_kg)}/kg</span></div>${r.notes?`<div class="feed-note">${esc(r.notes)}</div>`:''}</div><div><strong>${euro(costRow(r))}/dia</strong></div></article>`).join(''):'<p class="muted">Ainda não há registos.</p>'}</section></main>`}

function renderForm(){ensureStyle();const root=document.querySelector('#app');const lastMilk=latestMilk();root.innerHTML=`<main class="app"><button class="secondary" type="button" data-feed-action="cancel">← Cancelar</button><h1>🌾 Registar alimento</h1><section class="card"><form id="feedForm" class="feed-form"><div class="feed-form-row"><label>Data<input id="feedDate" type="date" value="${today()}" required></label><label>Tipo<select id="feedType"><option>Ração</option><option>Milho</option><option>Silagem de erva</option><option>Silagem de milho</option><option>Polpa de beterraba</option><option>Feno</option><option>Palha</option><option>Pastagem</option><option>Outro</option></select></label></div><label>Produto / descrição<input id="feedName" placeholder="Ex.: Especial Grão"></label><div class="feed-form-row"><label>Kg por vaca/dia<input id="feedKg" type="number" inputmode="decimal" min="0" step="0.01" required></label><label>N.º vacas alimentadas<input id="feedCows" type="number" inputmode="numeric" min="0" step="1" value="${Number(lastMilk?.milking_cows||0)||''}"></label></div><label>Preço por kg (€)<input id="feedPrice" type="number" inputmode="decimal" min="0" step="0.001" required></label><label>Observações<textarea id="feedNotes" maxlength="2000"></textarea></label><p class="feed-note">Para pastagem sem custo direto, pode colocar 0 €/kg. O custo/L usa a produção da mesma data quando existir.</p><button type="submit">Guardar alimentação</button><p id="feedMsg" class="muted"></p></form></section></main>`}

async function save(){const sb=window.lavouraSupabase;const msg=document.querySelector('#feedMsg');const record_date=document.querySelector('#feedDate')?.value;const kg=Number(document.querySelector('#feedKg')?.value||0);const price=Number(document.querySelector('#feedPrice')?.value||0);if(!record_date||kg<0||price<0){msg.textContent='Verifique a data, quantidade e preço.';return}msg.textContent='A guardar…';const row={farm_id:FARM_ID,record_date,feed_type:document.querySelector('#feedType').value,product_name:document.querySelector('#feedName').value.trim()||null,kg_per_cow:kg,cows_fed:Number(document.querySelector('#feedCows').value||0)||null,price_per_kg:price,notes:document.querySelector('#feedNotes').value.trim()||null};const{error}=await sb.from('feed_records').insert(row);if(error){msg.textContent='Erro: '+error.message;return}await load();render()}

async function openFeed(){if(busy)return;busy=true;try{await load();render()}catch(e){alert('Não foi possível abrir Alimentação: '+e.message)}finally{busy=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-feed-action]');if(!b)return;e.preventDefault();const a=b.dataset.feedAction;if(a==='open')openFeed();if(a==='new')renderForm();if(a==='cancel')render();if(a==='back'){document.querySelector('[data-action="mais"]')?.click()||location.reload()}})
document.addEventListener('submit',e=>{if(e.target?.id!=='feedForm')return;e.preventDefault();save()})
let queued=false;function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;addMoreEntry()})}new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});addMoreEntry()
