const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
const STYLE_ID='health-tools-style'
let animals=[]
let records=[]
let busy=false

function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.health-hero{margin:14px 0 16px;padding:18px;border-radius:20px;background:linear-gradient(135deg,#245c3b,#34754e);color:#fff;box-shadow:0 9px 25px rgba(36,92,59,.16)}.health-hero-label{font-size:12px;font-weight:800;opacity:.8}.health-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:13px}.health-stat{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.16);border-radius:14px;padding:12px 9px}.health-stat span{display:block;font-size:10px;color:rgba(255,255,255,.78);font-weight:750;line-height:1.2}.health-stat strong{display:block;font-size:23px;color:#fff;margin-top:4px}.health-alert{border:1px solid #f0d1d1!important;background:#fffafa!important}.health-alert h2{color:#8f3030}.health-record{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:start}.health-form{display:grid;gap:12px}.health-form label{display:grid;gap:6px;font-weight:700}.health-form input,.health-form select,.health-form textarea{width:100%;box-sizing:border-box}.health-form textarea{min-height:90px}.health-form-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.health-note{font-size:12px;color:#68756d;line-height:1.4}.health-pill{display:inline-flex;padding:5px 8px;border-radius:999px;background:#edf6f0;color:#245c3b;font-size:11px;font-weight:800;margin:4px 4px 2px 0}.health-history-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.health-cost{font-size:14px;color:#245c3b}.health-primary{width:100%;background:#245c3b!important;color:#fff!important;border:0!important;font-weight:800!important;min-height:48px}.health-withdrawal{padding:9px 11px;border-radius:11px;background:#fceeee;color:#8f3030;font-size:12px;font-weight:750;margin-top:8px}
@media(max-width:560px){.health-form-row{grid-template-columns:1fr}.health-record{grid-template-columns:1fr}.health-form button{min-height:48px}.health-grid{gap:6px}.health-stat{padding:10px 7px}.health-stat strong{font-size:21px}}
`;document.head.appendChild(s)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function today(){return new Date().toISOString().slice(0,10)}
function ptDate(v){if(!v)return'—';const[y,m,d]=String(v).slice(0,10).split('-');return d&&m?`${d}/${m}/${y}`:v}
function activeUntil(v){return Boolean(v&&String(v).slice(0,10)>=today())}
function animalNumber(id){return animals.find(a=>String(a.id)===String(id))?.number||'—'}
function screenText(){return(document.querySelector('main.app')?.innerText||'').toLowerCase()}
function isMore(){const t=screenText();return t.includes('mais')&&t.includes('definições')}
async function load(){const sb=window.lavouraSupabase;if(!sb)throw new Error('Supabase indisponível');const[a,r]=await Promise.all([sb.from('animals').select('id,number,name').eq('farm_id',FARM_ID).order('number'),sb.from('health_records').select('*').eq('farm_id',FARM_ID).order('event_date',{ascending:false}).order('created_at',{ascending:false})]);if(a.error)throw a.error;if(r.error)throw r.error;animals=a.data||[];records=r.data||[]}
function addMoreEntry(){if(!isMore()||document.querySelector('[data-health-entry]'))return;const main=document.querySelector('main.app');if(!main)return;const card=document.createElement('section');card.className='card';card.dataset.healthEntry='1';card.innerHTML=`<h2>🩺 Saúde e tratamentos</h2><p>Doenças, mastites, medicamentos, vacinas, desparasitações e períodos de carência.</p><button class="primary" type="button" data-health-action="open">Abrir saúde</button>`;const back=[...main.querySelectorAll('button')].find(b=>b.textContent.includes('Voltar'));if(back)back.insertAdjacentElement('beforebegin',card);else main.appendChild(card)}
function render(){ensureStyle();const main=document.querySelector('#app');if(!main)return;const milkActive=records.filter(r=>activeUntil(r.milk_withdrawal_until));const meatActive=records.filter(r=>activeUntil(r.meat_withdrawal_until));const recent=records.slice(0,30);main.innerHTML=`<main class="app"><button class="secondary" type="button" data-health-action="back">← Voltar</button><h1>🩺 Saúde</h1><p class="subtitle">Tratamentos, carências e histórico sanitário</p><section class="health-hero"><span class="health-hero-label">RESUMO SANITÁRIO</span><div class="health-grid"><div class="health-stat"><span>REGISTOS</span><strong>${records.length}</strong></div><div class="health-stat"><span>CARÊNCIA LEITE</span><strong>${milkActive.length}</strong></div><div class="health-stat"><span>CARÊNCIA CARNE</span><strong>${meatActive.length}</strong></div></div></section>${milkActive.length?`<section class="card health-alert"><h2>⚠️ Leite em carência</h2>${milkActive.map(r=>`<div class="health-withdrawal"><strong>🐄 ${esc(animalNumber(r.animal_id))}</strong> · até ${ptDate(r.milk_withdrawal_until)}${r.medication?` · ${esc(r.medication)}`:''}</div>`).join('')}</section>`:''}<section class="card"><button class="health-primary" type="button" data-health-action="new">＋ Novo registo de saúde</button></section><section class="card"><div class="health-history-head"><h2>Histórico</h2><span class="muted">Últimos ${Math.min(recent.length,30)}</span></div>${recent.length?recent.map(r=>`<article class="cow-card health-record"><div><strong>🐄 ${esc(animalNumber(r.animal_id))} · ${esc(r.category)}</strong><div class="muted">${ptDate(r.event_date)}${r.diagnosis?` · ${esc(r.diagnosis)}`:''}</div>${r.medication?`<div><span class="health-pill">💊 ${esc(r.medication)}</span>${r.dose?`<span class="health-pill">${esc(r.dose)}</span>`:''}${r.route?`<span class="health-pill">${esc(r.route)}</span>`:''}</div>`:''}${r.milk_withdrawal_until?`<div class="health-withdrawal">🥛 Carência até ${ptDate(r.milk_withdrawal_until)}</div>`:''}${r.notes?`<div class="health-note">${esc(r.notes)}</div>`:''}</div><div class="right health-cost">${Number(r.cost)>0?`<strong>${Number(r.cost).toLocaleString('pt-PT',{style:'currency',currency:'EUR'})}</strong>`:''}</div></article>`).join(''):'<p class="muted">Ainda não há registos de saúde.</p>'}</section></main>`}
function renderForm(){ensureStyle();const root=document.querySelector('#app');root.innerHTML=`<main class="app"><button class="secondary" type="button" data-health-action="cancel">← Cancelar</button><h1>🩺 Novo registo</h1><p class="subtitle">Registe o tratamento e as carências indicadas</p><section class="card"><form class="health-form" id="healthForm"><label>Vaca<select id="healthAnimal" required><option value="">Selecionar…</option>${animals.map(a=>`<option value="${a.id}">${esc(a.number)}${a.name?` — ${esc(a.name)}`:''}</option>`).join('')}</select></label><div class="health-form-row"><label>Data<input id="healthDate" type="date" value="${today()}" required></label><label>Tipo<select id="healthCategory"><option>Tratamento</option><option>Mastite</option><option>Doença</option><option>Vacina</option><option>Desparasitação</option><option>Preventivo</option><option>Outro</option></select></label></div><label>Problema / diagnóstico<input id="healthDiagnosis" placeholder="Ex.: mastite quarto traseiro direito"></label><div class="health-form-row"><label>Medicamento<input id="healthMedication" placeholder="Nome do medicamento"></label><label>Dose<input id="healthDose" placeholder="Ex.: 10 ml"></label></div><label>Via de administração<select id="healthRoute"><option value="">—</option><option>Intramuscular</option><option>Subcutânea</option><option>Intravenosa</option><option>Intramamária</option><option>Oral</option><option>Tópica</option><option>Outra</option></select></label><div class="health-form-row"><label>Carência leite até<input id="healthMilkUntil" type="date"></label><label>Carência carne até<input id="healthMeatUntil" type="date"></label></div><label>Custo (€)<input id="healthCost" type="number" inputmode="decimal" min="0" step="0.01" value="0"></label><label>Observações<textarea id="healthNotes" maxlength="2000"></textarea></label><p class="health-note">Use as datas de carência indicadas no medicamento/veterinário. A Lavoura+ regista e avisa; não calcula a carência clínica.</p><button class="health-primary" type="submit">Guardar registo</button><p id="healthMsg" class="muted"></p></form></section></main>`}
async function save(){const sb=window.lavouraSupabase;const msg=document.querySelector('#healthMsg');const animal_id=document.querySelector('#healthAnimal')?.value;const event_date=document.querySelector('#healthDate')?.value;if(!animal_id||!event_date){msg.textContent='Selecione a vaca e a data.';return}msg.textContent='A guardar…';const row={farm_id:FARM_ID,animal_id,event_date,category:document.querySelector('#healthCategory').value,diagnosis:document.querySelector('#healthDiagnosis').value.trim()||null,medication:document.querySelector('#healthMedication').value.trim()||null,dose:document.querySelector('#healthDose').value.trim()||null,route:document.querySelector('#healthRoute').value||null,milk_withdrawal_until:document.querySelector('#healthMilkUntil').value||null,meat_withdrawal_until:document.querySelector('#healthMeatUntil').value||null,cost:Number(document.querySelector('#healthCost').value||0),notes:document.querySelector('#healthNotes').value.trim()||null};const{error}=await sb.from('health_records').insert(row);if(error){msg.textContent='Erro: '+error.message;return}await load();render()}
async function openHealth(){if(busy)return;busy=true;try{await load();render()}catch(e){alert('Não foi possível abrir Saúde: '+e.message)}finally{busy=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-health-action]');if(!b)return;e.preventDefault();const a=b.dataset.healthAction;if(a==='open')openHealth();if(a==='new')renderForm();if(a==='cancel')render();if(a==='back'){document.querySelector('[data-action="mais"]')?.click()||location.reload()}})
document.addEventListener('submit',e=>{if(e.target?.id!=='healthForm')return;e.preventDefault();save()})
let queued=false;function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;addMoreEntry()})}new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});addMoreEntry()
