import './milk-ocr.css'
import './milk-history.js'

const FIELD_MAP={analysis_date:'analysisDate',fat:'analysisFat',protein:'analysisProtein',somatic_cells:'analysisSomaticCells',cfu:'analysisCfu'}
let tesseractPromise
function getMessage(){return document.querySelector('#fotografiaAnaliseMensagem')}
function setMessage(text,type=''){const m=getMessage();if(!m)return;m.textContent=text;m.classList.remove('loading','error');m.classList.add('milk-ocr-message');if(type)m.classList.add(type)}
function clearRecognizedState(){document.querySelectorAll('.ocr-recognized').forEach(f=>f.classList.remove('ocr-recognized'))}
function ensureRecognitionButton(){const i=document.querySelector('#fotografiaAnaliseLeite');if(!i||i.dataset.ocrReady==='true')return;i.dataset.ocrReady='true';i.setAttribute('accept','image/*');i.removeAttribute('capture');const p=document.querySelector('[data-action="fotografia-analise-leite"]');if(!p)return;p.textContent='🖼️ Escolher fotografia ou captura de ecrã';let b=document.querySelector('#processarFotografiaAnalise');if(!b){b=document.createElement('button');b.id='processarFotografiaAnalise';b.type='button';b.hidden=true;b.className='milk-ocr-button';b.textContent='✨ Ler novamente';p.insertAdjacentElement('afterend',b)}setMessage('Leitura gratuita. Nas tabelas GIL, a app calcula a média de todos os valores visíveis de MG, MP, células somáticas e UFC.')}
function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(tesseractPromise)return tesseractPromise;tesseractPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=()=>resolve(window.Tesseract);s.onerror=()=>reject(new Error('Não foi possível carregar o leitor gratuito.'));document.head.appendChild(s)});return tesseractPromise}
function normalizeNumber(v){if(!v)return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null}
function validFieldValue(name,value){if(value==null)return false;if(name==='analysis_date')return /^20\d{2}-[01]\d-[0-3]\d$/.test(String(value));const n=Number(value);if(!Number.isFinite(n)||n<0)return false;if(name==='fat')return n>=2&&n<=8;if(name==='protein')return n>=2&&n<=6;if(name==='somatic_cells'||name==='cfu')return n<=100000000;return false}
function average(values){if(!values.length)return null;return values.reduce((a,b)=>a+b,0)/values.length}
function round2(value){return Math.round(value*100)/100}
function parseGilMgMp(lines,clean,fields){if(!/\bMG\b/i.test(clean)||!/\bMP\b/i.test(clean))return;const rows=[];for(const line of lines){const decimals=[...line.matchAll(/\b([2-8][.,]\d{1,2})\b/g)].map(m=>normalizeNumber(m[1])).filter(v=>v!==null);for(let i=0;i<decimals.length-1;i++){const fat=decimals[i],protein=decimals[i+1];if(validFieldValue('fat',fat)&&validFieldValue('protein',protein)){rows.push({fat,protein});break}}}if(rows.length){fields.fat=round2(average(rows.map(r=>r.fat)));fields.protein=round2(average(rows.map(r=>r.protein)));fields._gil_mgmp_rows=rows.length}}
function parseGilX1000(lines,clean,fields){if(!/X\s*1000/i.test(clean)||!/(C[EÉ]L|CEL)/i.test(clean)||!/UFC/i.test(clean))return;const rows=[];for(const line of lines){const nums=[...line.matchAll(/\b(\d{1,6})\b/g)].map(m=>Number(m[1]));if(nums.length>=3){const day=nums[nums.length-3],cells=nums[nums.length-2],cfu=nums[nums.length-1];if(day>=1&&day<=31&&cells>=50&&cells<=5000&&cfu>=0&&cfu<=5000)rows.push({cells,cfu})}else if(nums.length===2){const cells=nums[0],cfu=nums[1];if(cells>=50&&cells<=5000&&cfu>=0&&cfu<=5000)rows.push({cells,cfu})}}if(rows.length){const cellsAvg=average(rows.map(r=>r.cells)),cfuAvg=average(rows.map(r=>r.cfu));if(fields.somatic_cells==null)fields.somatic_cells=Math.round(cellsAvg);if(fields.cfu==null)fields.cfu=Math.round(cfuAvg);fields._gil_x1000_rows=rows.length}}
function parseMilkText(text){const clean=text.replace(/\r/g,'').replace(/[|]/g,' '),lines=clean.split('\n').map(l=>l.replace(/\s+/g,' ').trim()).filter(Boolean),fields={};const labeledNumber=(labels,integer=false)=>{const r=new RegExp(`(?:${labels.join('|')})[^0-9]{0,20}([0-9]+(?:[.,][0-9]+)?)`,'i'),m=clean.match(r);if(!m)return null;const v=normalizeNumber(m[1]);return integer&&v!==null?Math.round(v):v};const fat=labeledNumber(['MG','gordura','mat[eé]ria\\s+gorda']),protein=labeledNumber(['MP','prote[ií]na']),somatic=labeledNumber(['c[eé]lulas\\s+som[aá]ticas','som[aá]ticas','CCS'],true),cfu=labeledNumber(['UFC','germes','contagem\\s+total'],true);if(validFieldValue('fat',fat))fields.fat=fat;if(validFieldValue('protein',protein))fields.protein=protein;if(!/X\s*1000/i.test(clean)){if(validFieldValue('somatic_cells',somatic))fields.somatic_cells=somatic;if(validFieldValue('cfu',cfu))fields.cfu=cfu}const dm=clean.match(/\b(20\d{2})[-\/]([01]?\d)[-\/]([0-3]?\d)\b/)||clean.match(/\b([0-3]?\d)[-\/]([01]?\d)[-\/](20\d{2})\b/);if(dm){const d=dm[1].length===4?`${dm[1]}-${dm[2].padStart(2,'0')}-${dm[3].padStart(2,'0')}`:`${dm[3]}-${dm[2].padStart(2,'0')}-${dm[1].padStart(2,'0')}`;if(validFieldValue('analysis_date',d))fields.analysis_date=d}parseGilMgMp(lines,clean,fields);parseGilX1000(lines,clean,fields);return fields}
function currentFieldIsUsable(name,input){if(!input?.value)return false;if(name==='analysis_date')return validFieldValue(name,input.value);return validFieldValue(name,normalizeNumber(input.value))}
function fillField(name,value,recognized,preserved){if(!validFieldValue(name,value))return;const input=document.querySelector(`#${FIELD_MAP[name]}`);if(!input)return;if(currentFieldIsUsable(name,input)){preserved.push(name);return}input.value=String(value);input.classList.add('ocr-recognized');recognized.push(name)}
async function recognizeMilkReport(){const input=document.querySelector('#fotografiaAnaliseLeite'),button=document.querySelector('#processarFotografiaAnalise'),file=input?.files?.[0];if(!file){setMessage('Escolha primeiro uma fotografia ou captura de ecrã.','error');return}if(button)button.disabled=true;clearRecognizedState();setMessage('🔎 A fazer leitura gratuita da captura…','loading');try{const Tesseract=await loadTesseract(),result=await Tesseract.recognize(file,'eng',{logger:p=>{if(p.status==='recognizing text'&&typeof p.progress==='number')setMessage(`🔎 A ler a captura… ${Math.round(p.progress*100)}%`,'loading')}}),fields=parseMilkText(result?.data?.text||''),recognized=[],preserved=[];Object.keys(FIELD_MAP).forEach(n=>fillField(n,fields[n],recognized,preserved));if(!recognized.length){if(preserved.length){setMessage('✅ A captura foi lida, mas os valores encontrados já estavam preenchidos. Pode escolher outra captura.');return}setMessage('Não encontrei valores seguros nesta captura. Tente aproximar a captura das colunas e dos valores.','error');return}const remaining=Object.entries(FIELD_MAP).filter(([,id])=>!document.querySelector(`#${id}`)?.value).map(([n])=>n);const infos=[];if(fields._gil_mgmp_rows)infos.push(`MG/MP: média de ${fields._gil_mgmp_rows} linhas visíveis`);if(fields._gil_x1000_rows)infos.push(`células/UFC: média de ${fields._gil_x1000_rows} linhas visíveis, na unidade X1000 do GIL`);const extra=infos.length?` ${infos.join(' · ')}.`:'';setMessage((remaining.length?`✅ ${recognized.length} campo(s) preenchido(s). Pode escolher outra captura para completar os ${remaining.length} campo(s) em falta.`:'✅ Análise preenchida. Confirme todos os valores antes de guardar.')+extra)}catch(e){console.error('OCR gratuito análises do leite:',e);setMessage(e?.message||'Não foi possível ler esta captura.','error')}finally{if(button)button.disabled=false}}
const observer=new MutationObserver(()=>ensureRecognitionButton());observer.observe(document.body,{childList:true,subtree:true});ensureRecognitionButton();document.addEventListener('change',e=>{if(e.target?.id!=='fotografiaAnaliseLeite')return;const b=document.querySelector('#processarFotografiaAnalise'),f=e.target.files?.[0];if(!b)return;if(!f){b.hidden=true;setMessage('Nenhuma imagem selecionada.');return}b.hidden=false;recognizeMilkReport()});document.addEventListener('click',e=>{const b=e.target.closest('#processarFotografiaAnalise');if(!b)return;e.preventDefault();recognizeMilkReport()})
