const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
const NS='http://www.w3.org/2000/svg'
function datePT(v){if(!v)return '—';const p=String(v).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v}
function daysBetween(a,b){return Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000)}
function todayISO(){return new Date().toISOString().slice(0,10)}
function polar(cx,cy,r,deg){const a=(deg-90)*Math.PI/180;return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}}
function arcPath(cx,cy,r,start,end){const a=polar(cx,cy,r,end),b=polar(cx,cy,r,start),large=end-start<=180?0:1;return`M ${b.x} ${b.y} A ${r} ${r} 0 ${large} 1 ${a.x} ${a.y}`}
function svgEl(tag,attrs={}){const el=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el}
function latestByType(events,type){return events.filter(e=>e.event_type===type).sort((a,b)=>String(b.event_date||'').localeCompare(String(a.event_date||'')))[0]||null}
function stageFor(ia,animal){const d=ia?.event_date?daysBetween(ia.event_date,todayISO()):null;if(animal?.status==='SECA')return{key:'dry',label:'SECA',color:'#34a853'};if(ia?.result&&String(ia.result).toLowerCase().includes('vazia'))return{key:'red',label:'VAZIA',color:'#e53935'};if(d===null)return{key:'red',label:'SEM IA',color:'#9aa0a6'};if(d<30)return{key:'recent',label:'IA RECENTE',color:'#f4c20d'};if(d<90)return{key:'diag',label:'DIAGNÓSTICO',color:'#f39c12'};if(d<223)return{key:'preg',label:'PRENHE',color:'#2f80ed'};return{key:'red',label:'PRÉ-PARTO',color:'#e53935'}}
const SECTORS={recent:[220,266],diag:[266,300],preg:[300,420],dry:[60,125],red:[125,220]}
async function loadWheelData(){const sb=window.lavouraSupabase;if(!sb)return[];const{data:animals,error:aErr}=await sb.from('animals').select('id,number,name,status').eq('farm_id',FARM_ID);if(aErr||!animals?.length)return[];const ids=animals.map(a=>a.id);const{data:events,error:eErr}=await sb.from('reproduction').select('animal_id,event_type,event_date,result,expected_dry_off,expected_calving').eq('farm_id',FARM_ID).in('animal_id',ids);if(eErr)return[];return animals.map(a=>{const ev=(events||[]).filter(e=>e.animal_id===a.id),ia=latestByType(ev,'IA'),dry=latestByType(ev,'SECAGEM'),calving=latestByType(ev,'PARTO');return{animal:a,ia,dry,calving,stage:stageFor(ia,a)}}).filter(x=>x.ia||x.dry||x.calving)}
function showInfo(host,item){let box=host.querySelector('.rw-info');if(!box){box=document.createElement('div');box.className='rw-info';host.appendChild(box)}box.innerHTML=`<button type="button" class="rw-close">×</button><strong>🐄 ${item.animal.name||item.animal.number}</strong><div>Brinco: ${item.animal.number}</div><div>${item.stage.label}</div><div>IA: ${datePT(item.ia?.event_date)}</div><div>Secagem prevista: ${datePT(item.ia?.expected_dry_off)}</div><div>Parto previsto: ${datePT(item.ia?.expected_calving)}</div>`;box.querySelector('.rw-close').onclick=()=>box.remove()}
function summary(items){const c={recent:0,diag:0,preg:0,dry:0,red:0};items.forEach(x=>c[x.stage.key]=(c[x.stage.key]||0)+1);const s=document.createElement('section');s.className='rw-summary';s.innerHTML=`<div><b style="color:#f4b400">${c.recent+c.diag}</b><span>IA / diagnóstico</span></div><div><b style="color:#2f80ed">${c.preg}</b><span>Prenhes</span></div><div><b style="color:#34a853">${c.dry}</b><span>Secas</span></div><div><b style="color:#e53935">${c.red}</b><span>Pré-parto / vazias</span></div>`;return s}
function buildWheel(items){const host=document.createElement('section');host.className='card reproduction-wheel-card';host.dataset.reproductionWheel='1';host.innerHTML='<div class="rw-card-head"><div><h2><span class="rw-wheel-icon">◉</span> Roda da Reprodução</h2><p class="muted rw-subtitle">Situação reprodutiva atual do rebanho</p></div></div>';const wrap=document.createElement('div');wrap.className='rw-wrap';host.appendChild(wrap);const svg=svgEl('svg',{viewBox:'0 0 600 620',role:'img','aria-label':'Roda da Reprodução'});wrap.appendChild(svg);const cx=300,cy=310;svg.appendChild(svgEl('circle',{cx,cy,r:235,fill:'#fff',stroke:'#c5d0ca','stroke-width':2}));svg.appendChild(svgEl('circle',{cx,cy,r:75,fill:'#fff',stroke:'#cbd5d0','stroke-width':2}));[[300,420,'#2f80ed'],[60,125,'#34a853'],[125,220,'#e53935'],[220,266,'#f4c20d'],[266,300,'#f39c12']].forEach(([s,e,c])=>svg.appendChild(svgEl('path',{d:arcPath(cx,cy,247,s,e),fill:'none',stroke:c,'stroke-width':18})));for(let i=0;i<60;i++){const deg=i*6,p1=polar(cx,cy,82,deg),p2=polar(cx,cy,232,deg);svg.appendChild(svgEl('line',{x1:p1.x,y1:p1.y,x2:p2.x,y2:p2.y,stroke:i%5===0?'#aeb9b3':'#dde3e0','stroke-width':i%5===0?1.2:.7}))}const title=svgEl('text',{x:cx,y:cy-8,'text-anchor':'middle','font-size':22,'font-weight':'800',fill:'#245c3b'});title.textContent='Lavoura+';svg.appendChild(title);const count=svgEl('text',{x:cx,y:cy+23,'text-anchor':'middle','font-size':14,fill:'#68736e'});count.textContent=`${items.length} animais`;svg.appendChild(count);
 const groups={recent:[],diag:[],preg:[],dry:[],red:[]};items.forEach(x=>(groups[x.stage.key]||groups.red).push(x));Object.values(groups).forEach(arr=>arr.sort((a,b)=>String(a.animal.name||a.animal.number).localeCompare(String(b.animal.name||b.animal.number),'pt',{sensitivity:'base'})));
 Object.entries(groups).forEach(([key,arr])=>{const [start,end]=SECTORS[key];const margin=5;arr.forEach((item,i)=>{const deg=arr.length===1?(start+end)/2:start+margin+((end-start-margin*2)*(i/(arr.length-1)));const lane=i%3;const r=206-lane*24;const p=polar(cx,cy,r,deg);const g=svgEl('g',{tabindex:'0',role:'button','aria-label':item.animal.name||String(item.animal.number)});g.style.cursor='pointer';g.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:7.5,fill:item.stage.color,stroke:'#fff','stroke-width':2}));let label=(item.animal.name||String(item.animal.number)).trim();if(label.length>13)label=label.slice(0,12)+'…';const left=((deg%360)+360)%360>180;const tx=p.x+(left?-10:10),ty=p.y+3;const text=svgEl('text',{x:tx,y:ty,'font-size':9.5,'font-weight':'700',fill:'#26332d','text-anchor':left?'end':'start'});text.textContent=label;g.appendChild(text);g.addEventListener('click',()=>showInfo(host,item));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showInfo(host,item)}});svg.appendChild(g)})});
 const legend=document.createElement('div');legend.className='rw-legend';legend.innerHTML='<span><i style="background:#f4c20d"></i>IA recente</span><span><i style="background:#f39c12"></i>Diagnóstico</span><span><i style="background:#2f80ed"></i>Prenhe</span><span><i style="background:#34a853"></i>Seca</span><span><i style="background:#e53935"></i>Pré-parto / vazia</span>';host.appendChild(legend);const help=document.createElement('div');help.className='rw-help';help.innerHTML='<b>ⓘ Como interpretar</b><span>Cada ponto representa uma vaca e a cor indica a fase reprodutiva atual.</span>';host.appendChild(help);return host}
function ensureStyles(){if(document.querySelector('#reproduction-wheel-style'))return;const s=document.createElement('style');s.id='reproduction-wheel-style';s.textContent=`.reproduction-wheel-card{position:relative;overflow:hidden}.rw-card-head h2,.reproduction-wheel-card h2{display:flex;align-items:center;gap:8px;margin-bottom:4px}.rw-wheel-icon{display:inline-grid;place-items:center;width:28px;height:28px;border:4px solid #2f80ed;border-right-color:#34a853;border-bottom-color:#e53935;border-radius:50%;font-size:10px;color:#f4c20d}.rw-subtitle{margin:0 0 8px}.rw-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.rw-summary>div{background:#fff;border:1px solid #e2e8e4;border-radius:14px;padding:10px 6px;text-align:center;box-shadow:0 3px 10px rgba(0,0,0,.05)}.rw-summary b{display:block;font-size:23px}.rw-summary span{display:block;font-size:11px;color:#65716b;line-height:1.2}.rw-wrap{width:100%;overflow:hidden}.rw-wrap svg{display:block;width:100%;max-width:620px;height:auto;margin:0 auto}.rw-legend{display:flex;flex-wrap:wrap;gap:8px 14px;margin-top:8px;font-size:13px;color:#56615c}.rw-legend span{display:flex;align-items:center;gap:6px}.rw-legend i{width:10px;height:10px;border-radius:50%;display:inline-block}.rw-help{margin-top:12px;padding:12px;border-radius:14px;background:#f5faf7;color:#315943;display:grid;gap:3px}.rw-help span{font-size:12px;color:#65716b}.rw-info{position:absolute;left:18px;right:18px;top:90px;background:#fff;border:1px solid #dce5e0;border-radius:16px;padding:16px 42px 16px 16px;box-shadow:0 12px 30px rgba(0,0,0,.16);z-index:5;line-height:1.55}.rw-close{position:absolute;right:9px;top:7px;border:0;background:transparent;font-size:28px;color:#56615c}@media(max-width:620px){.reproduction-wheel-card{padding-left:8px!important;padding-right:8px!important}.rw-wrap svg{width:100%;min-width:0}.rw-legend{padding:0 6px;font-size:12px}.rw-summary{gap:5px}.rw-summary>div{padding:8px 3px}.rw-summary b{font-size:20px}.rw-summary span{font-size:10px}}`;document.head.appendChild(s)}
function changeReproductionIcon(main){const h1=[...main.querySelectorAll('h1')].find(x=>/Reprodução/i.test(x.textContent||''));if(h1&&!h1.dataset.wheelIcon){h1.dataset.wheelIcon='1';h1.innerHTML='<span class="rw-wheel-icon">◉</span> Reprodução'}return h1}
let mounting=false;async function mount(){if(mounting)return;const main=document.querySelector('#app main');if(!main)return;ensureStyles();const h1=changeReproductionIcon(main);if(!h1||main.querySelector('[data-reproduction-wheel]'))return;mounting=true;try{const items=await loadWheelData();const oldStats=main.querySelector('.stats-grid');if(oldStats)oldStats.style.display='none';const sum=summary(items);h1.insertAdjacentElement('afterend',sum);sum.insertAdjacentElement('afterend',buildWheel(items))}finally{mounting=false}}
mount();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;mount()})}).observe(document.body,{childList:true,subtree:true})