const FARM_ID='72bb5d54-f614-4394-8da9-7113a8e48a29'
const NS='http://www.w3.org/2000/svg',CX=300,CY=305,TERM=283,START=180
const ZONES=[{a:0,b:83,color:'#e31b23',key:'red',label:'0–83 dias'},{a:83,b:120,color:'#ffd400',key:'recent',label:'83–120 dias'},{a:120,b:240,color:'#1687e8',key:'preg',label:'120–240 dias'},{a:240,b:283,color:'#39a94b',key:'dry',label:'240–283 dias'}]
function el(t,a={}){const n=document.createElementNS(NS,t);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n}
function polar(r,d){const a=(d-90)*Math.PI/180;return{x:CX+r*Math.cos(a),y:CY+r*Math.sin(a)}}
function arc(r,s,e){const a=polar(r,s),b=polar(r,e);return`M ${a.x} ${a.y} A ${r} ${r} 0 ${e-s>180?1:0} 1 ${b.x} ${b.y}`}
function today(){return new Date().toISOString().slice(0,10)}
function days(a,b){return Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000)}
function pt(v){if(!v)return'—';const p=String(v).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v}
function latest(ev){return ev.filter(x=>x.event_type==='IA').sort((a,b)=>String(b.event_date||'').localeCompare(String(a.event_date||''))||String(b.created_at||'').localeCompare(String(a.created_at||'')))[0]||null}
function last4(v){const s=String(v??'').replace(/\D/g,'');return(s.slice(-4)||'—').padStart(Math.min(4,s.length||1),'0')}
function zone(day){return ZONES.find(z=>day>=z.a&&day<(z.b===TERM?z.b+1:z.b))||null}
async function data(){const sb=window.lavouraSupabase;if(!sb)return[];const{data:animals}=await sb.from('animals').select('id,number,name,status').eq('farm_id',FARM_ID);if(!animals?.length)return[];const ids=animals.map(a=>a.id);const{data:events}=await sb.from('reproduction').select('animal_id,event_type,event_date,result,expected_dry_off,expected_calving,created_at').eq('farm_id',FARM_ID).in('animal_id',ids);return animals.map(animal=>{const ia=latest((events||[]).filter(e=>e.animal_id===animal.id));const day=ia?.event_date?days(ia.event_date,today()):null;return{animal,ia,day,z:Number.isFinite(day)&&day>=0&&day<=TERM?zone(day):null}})}
function info(host,x){let b=host.querySelector('.rw-info');if(!b){b=document.createElement('div');b.className='rw-info';host.appendChild(b)}b.innerHTML=`<button class="rw-close">×</button><strong>🐄 ${x.animal.name||x.animal.number}</strong><div>Brinco: ${x.animal.number}</div><div>Última IA: ${pt(x.ia?.event_date)}</div><div>Dias: ${Number.isFinite(x.day)?x.day:'—'}</div><div>Secagem prevista: ${pt(x.ia?.expected_dry_off)}</div><div>Parto previsto: ${pt(x.ia?.expected_calving)}</div>`;b.querySelector('.rw-close').onclick=()=>b.remove()}
function lanes(items){const s=[...items].sort((a,b)=>a.day-b.day),active=[];return s.map(x=>{for(let i=active.length-1;i>=0;i--)if(x.day-active[i].day>7)active.splice(i,1);const used=new Set(active.map(v=>v.l));let l=0;while(used.has(l)&&l<6)l++;active.push({day:x.day,l});return{...x,l:l%6}})}
function animal(svg,host,x,p,color){const g=el('g',{role:'button',tabindex:'0','aria-label':`${x.animal.name||''} ${x.animal.number||''}`});g.style.cursor='pointer';g.appendChild(el('circle',{cx:p.x,cy:p.y,r:11,fill:color,stroke:'#111','stroke-width':'1'}));const t=el('text',{x:p.x,y:p.y+3.3,'text-anchor':'middle','font-size':'8.5','font-weight':'900',fill:'#fff'});t.textContent=last4(x.animal.number);g.appendChild(t);g.onclick=()=>info(host,x);svg.appendChild(g)}
function wheel(items){const host=document.createElement('section');host.className='card reproduction-wheel-card';host.dataset.reproductionWheel='1';host.innerHTML='<div class="rw-card-head"><h2><span class="rw-wheel-icon">◉</span> Roda da Reprodução</h2><p class="muted">Situação reprodutiva atual do rebanho</p></div>';const wrap=document.createElement('div');wrap.className='rw-wrap';host.appendChild(wrap);const svg=el('svg',{viewBox:'0 0 600 650'});wrap.appendChild(svg)
svg.appendChild(el('circle',{cx:CX,cy:CY,r:236,fill:'#fff',stroke:'#111','stroke-width':'1.7'}));ZONES.forEach(z=>svg.appendChild(el('path',{d:arc(248,START+z.a/TERM*360,START+z.b/TERM*360),fill:'none',stroke:z.color,'stroke-width':'18'})));svg.appendChild(el('circle',{cx:CX,cy:CY,r:258,fill:'none',stroke:'#111'}));svg.appendChild(el('circle',{cx:CX,cy:CY,r:224,fill:'none',stroke:'#111'}))
for(let d=0;d<TERM;d+=7){const q=START+d/TERM*360,a=polar(67,q),b=polar(235,q);svg.appendChild(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:d%28===0?'#222':'#87908b','stroke-width':d%28===0?'1.15':'.6'}))}
for(let d=0;d<=270;d+=30){const q=START+d/TERM*360,a=polar(258,q),b=polar(269,q),p=polar(279,q);svg.appendChild(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#111','stroke-width':'1.4'}));const t=el('text',{x:p.x,y:p.y+3,'text-anchor':'middle','font-size':'10','font-weight':'700'});t.textContent=d;svg.appendChild(t)}
svg.appendChild(el('circle',{cx:CX,cy:CY,r:62,fill:'#fff',stroke:'#111','stroke-width':'1.6'}));let t=el('text',{x:CX,y:CY-4,'text-anchor':'middle','font-size':'21','font-weight':'900',fill:'#245c3b'});t.textContent='Lavoura+';svg.appendChild(t);t=el('text',{x:CX,y:CY+20,'text-anchor':'middle','font-size':'12',fill:'#59645f'});t.textContent=`${items.length} animais`;svg.appendChild(t)
const timed=items.filter(x=>x.z),untimed=items.filter(x=>!x.z);lanes(timed).forEach(x=>{const q=START+x.day/TERM*360,p=polar(210-x.l*25,q);animal(svg,host,x,p,x.z.color)});untimed.forEach((x,i)=>{const q=300+i/Math.max(1,untimed.length)*120,p=polar(103+(i%2)*19,q);animal(svg,host,x,p,'#777')})
for(const [y,txt,c] of [[598,'HOJE','#17833c'],[613,'PARTO','#111'],[629,'283','#e31b23']]){const e=el('text',{x:CX,y,'text-anchor':'middle','font-size':'11','font-weight':'900',fill:c});e.textContent=txt;svg.appendChild(e)}
const leg=document.createElement('div');leg.className='rw-legend';leg.innerHTML='<span><i style="background:#e31b23"></i>0–83 dias</span><span><i style="background:#ffd400"></i>83–120 dias</span><span><i style="background:#1687e8"></i>120–240 dias</span><span><i style="background:#39a94b"></i>240–283 dias</span>';host.appendChild(leg);return host}
function summary(items){const c={red:0,recent:0,preg:0,dry:0};items.forEach(x=>{if(x.z)c[x.z.key]++});const s=document.createElement('section');s.className='rw-summary';s.innerHTML=`<div><b style="color:#e31b23">${c.red}</b><span>0–83 dias</span></div><div><b style="color:#ffd400">${c.recent}</b><span>83–120 dias</span></div><div><b style="color:#1687e8">${c.preg}</b><span>120–240 dias</span></div><div><b style="color:#39a94b">${c.dry}</b><span>240–283 dias</span></div>`;return s}
function styles(){if(document.querySelector('#reproduction-wheel-style'))return;const s=document.createElement('style');s.id='reproduction-wheel-style';s.textContent='.reproduction-wheel-card{position:relative;overflow:hidden}.rw-card-head h2{display:flex;align-items:center;gap:8px;margin:0 0 4px}.rw-wheel-icon{display:inline-grid;place-items:center;width:28px;height:28px;border:4px solid #1687e8;border-right-color:#39a94b;border-bottom-color:#e31b23;border-left-color:#ffd400;border-radius:50%;font-size:10px;color:#ffd400}.rw-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.rw-summary>div{background:#fff;border:1px solid #e2e8e4;border-radius:14px;padding:10px 4px;text-align:center}.rw-summary b{display:block;font-size:22px}.rw-summary span{font-size:10px;color:#65716b}.rw-wrap svg{display:block;width:100%;max-width:650px;height:auto;margin:auto}.rw-legend{display:flex;flex-wrap:wrap;gap:8px 14px;padding:0 6px;font-size:12px}.rw-legend span{display:flex;align-items:center;gap:6px}.rw-legend i{width:11px;height:11px;border-radius:50%;border:1px solid #555}.rw-info{position:absolute;left:18px;right:18px;top:90px;background:#fff;border:1px solid #dce5e0;border-radius:16px;padding:16px 42px 16px 16px;box-shadow:0 12px 30px #0003;z-index:5;line-height:1.55}.rw-close{position:absolute;right:9px;top:7px;border:0;background:transparent;font-size:28px}@media(max-width:620px){.reproduction-wheel-card{padding-left:5px!important;padding-right:5px!important}.rw-summary{gap:5px}}';document.head.appendChild(s)}
function icon(main){const h=[...main.querySelectorAll('h1')].find(x=>/Reprodução/i.test(x.textContent||''));if(h&&!h.dataset.wheelIcon){h.dataset.wheelIcon='1';h.innerHTML='<span class="rw-wheel-icon">◉</span> Reprodução'}return h}
let mounting=false;async function mount(){if(mounting)return;const main=document.querySelector('#app main');if(!main)return;styles();const h=icon(main);if(!h||main.querySelector('[data-reproduction-wheel]'))return;mounting=true;try{const items=await data();const old=main.querySelector('.stats-grid');if(old)old.style.display='none';const s=summary(items);h.insertAdjacentElement('afterend',s);s.insertAdjacentElement('afterend',wheel(items))}finally{mounting=false}}
mount();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;mount()})}).observe(document.body,{childList:true,subtree:true})